# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
# 服务器目录与本地形成映射 var/lib/docker/volumes/orderer.wulusai.net 就跟 orderer.wulusai.net这台服务器形成映射
volumes:
  orderer.wulusai.net:
  peer0.org1.wulusai.net:
  peer1.org1.wulusai.net:
  peer0.org2.wulusai.net:
  peer1.org2.wulusai.net:

networks: #网络 所有的docker容器,必须在一个网络中才能通信
  byfn:

services: #服务

  ca.wulusai.net: #fabric-ca 的服务器名,随意
    image: hyperledger/fabric-ca:latest #镜像文件
    environment:
      #容器中的home目录
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      #fabric-ca的服务器名 自己取
      - FABRIC_CA_SERVER_CA_NAME=ca.wulusai.net
      #fabric-ca服务器证书文件目录中的证书文件 明确当前ca属于哪个组织
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.wulusai.net-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org1.wulusai.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.wulusai.net
    networks:
      - byfn

  orderer.wulusai.net: #为了方便看 服务名跟域名相同
    extends: #继承
      file:   base/docker-compose-base.yaml #继承的文件位置
      service: orderer.wulusai.net #继承文件中的服务
    container_name: orderer.wulusai.net #容器名字
    networks:
      - byfn

  peer0.org1.wulusai.net:
    container_name: peer0.org1.wulusai.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.wulusai.net
    networks:
      - byfn

  peer1.org1.wulusai.net:
    container_name: peer1.org1.wulusai.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.wulusai.net
    networks:
      - byfn

  peer0.org2.wulusai.net:
    container_name: peer0.org2.wulusai.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.wulusai.net
    networks:
      - byfn

  peer1.org2.wulusai.net:
    container_name: peer1.org2.wulusai.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.wulusai.net
    networks:
      - byfn

  cli: #客户端角色
    container_name: cli
    image: hyperledger/fabric-tools:latest #使用的容器 这个容器包含 fabric-sample/bin 目录下的所有工具 进入到这个容器中可以直接使用相关命令
    tty: true
    stdin_open: true
    environment: #环境变量
     # - SYS_CHANNEL=wulusaichannel  #$SYS_CHANNEL 操作的channel名
      - GOPATH=/opt/gopath #go的工作环境目录 不用改
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock #docker容器启动后对应守护进程的本地套接字,不用改
      - FABRIC_LOGGING_SPEC=DEBUG
      #- FABRIC_LOGGING_SPEC=INFO #日志级别
      - CORE_PEER_ID=cli #客户端节点的id 自己设
      - CORE_PEER_ADDRESS=peer0.org1.wulusai.net:7051 #客户端连接的peer节点
      - CORE_PEER_LOCALMSPID=Org1MSP #连接节点的所属的组织id
      - CORE_PEER_TLS_ENABLED=true #连接加密不加密
       #证书文件
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.wulusai.net/peers/peer0.org1.wulusai.net/tls/server.crt
      #私钥文件
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.wulusai.net/peers/peer0.org1.wulusai.net/tls/server.key
      #根证书文件
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.wulusai.net/peers/peer0.org1.wulusai.net/tls/ca.crt
      #当前客户端的身份
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.wulusai.net/users/Admin@org1.wulusai.net/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/ #不用管
        - ./chaincode/:/opt/gopath/src/github.com/chaincode #链码目录就直接当前目录的chaincode就可以
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/ #脚本,当前不用
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts #configtxgen 生成的文件都映射到这里
    depends_on: #规定服务的启动顺序
      - orderer.wulusai.net
      - peer0.org1.wulusai.net
      - peer1.org1.wulusai.net
      - peer0.org2.wulusai.net
      - peer1.org2.wulusai.net
    networks:
      - byfn
