# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.wulusai.net:
    container_name: orderer.wulusai.net
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/wulusai.net/orderers/orderer.wulusai.net/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/wulusai.net/orderers/orderer.wulusai.net/tls/:/var/hyperledger/orderer/tls
        - orderer.wulusai.net:/var/hyperledger/production/orderer
        #orderer.wulusai.net对应的是 var/lib/docker/volumes/orderer.wulusai.net 这个名称的映射关系还没搞懂
    ports:
      - 7050:7050

  peer0.org1.wulusai.net:
    container_name: peer0.org1.wulusai.net
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.wulusai.net #当前peer节点的名字 自己取
      - CORE_PEER_ADDRESS=peer0.org1.wulusai.net:7051 #当前peer节点的地址信息
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.wulusai.net:7052 #链码地址
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052 #链码的监听地址
     #节点启动后向那些地方发送gossip链接加入网络 一般写自己就行
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.wulusai.net:8051
      # 节点被组织外节点感知的地址 如果不指定外面就感知不到存在
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.wulusai.net:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.wulusai.net/peers/peer0.org1.wulusai.net/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.wulusai.net/peers/peer0.org1.wulusai.net/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.wulusai.net:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.org1.wulusai.net:
    container_name: peer1.org1.wulusai.net
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.wulusai.net
      - CORE_PEER_ADDRESS=peer1.org1.wulusai.net:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.wulusai.net:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.wulusai.net:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.wulusai.net:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.wulusai.net/peers/peer1.org1.wulusai.net/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.wulusai.net/peers/peer1.org1.wulusai.net/tls:/etc/hyperledger/fabric/tls
        - peer1.org1.wulusai.net:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.org2.wulusai.net:
    container_name: peer0.org2.wulusai.net
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.wulusai.net
      - CORE_PEER_ADDRESS=peer0.org2.wulusai.net:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.wulusai.net:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.wulusai.net:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.wulusai.net:10051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.wulusai.net/peers/peer0.org2.wulusai.net/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.wulusai.net/peers/peer0.org2.wulusai.net/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.wulusai.net:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.org2.wulusai.net:
    container_name: peer1.org2.wulusai.net
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.wulusai.net
      - CORE_PEER_ADDRESS=peer1.org2.wulusai.net:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.wulusai.net:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.wulusai.net:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.wulusai.net:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.wulusai.net/peers/peer1.org2.wulusai.net/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.wulusai.net/peers/peer1.org2.wulusai.net/tls:/etc/hyperledger/fabric/tls
        - peer1.org2.wulusai.net:/var/hyperledger/production
    ports:
      - 10051:10051
