# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
# 服务器目录与本地形成映射 var/lib/docker/volumes/orderer.wulusai.net 就跟 orderer.wulusai.net这台服务器形成映射
volumes:
  zookeeper1.wulusai.net:
  zookeeper2.wulusai.net:
  zookeeper3.wulusai.net:
  kafka1.wulusai.net:
  kafka2.wulusai.net:
  kafka3.wulusai.net:
  kafka4.wulusai.net:
  orderer1.wulusai.net:
  orderer2.wulusai.net:
  orderer3.wulusai.net:
  orderer0.wulusai.net:
  peer0.org1.wulusai.net:
#  peer1.org1.wulusai.net:
  peer0.org2.wulusai.net:
  #peer1.org2.wulusai.net:
  ca0.wulusai.net:
  ca1.wulusai.net:

networks: #网络 所有的docker容器,必须在一个网络中才能通信
  wulusai:

services: #服务

#ca
  ca0.wulusai.net: #fabric-ca 的服务器名,随意
    extends: #继承
      file:   docker-compose-peer0org1.yaml #继承的文件位置
      service: ca.wulusai.net #继承文件中的服务
    container_name: ca0.wulusai.net
    networks:
      - wulusai
    depends_on:
      - peer0.org1.wulusai.net

  ca1.wulusai.net: #fabric-ca 的服务器名,随意
    extends: #继承
      file:   docker-compose-peer0org2.yaml #继承的文件位置
      service: ca.wulusai.net #继承文件中的服务
    container_name: ca1.wulusai.net
    networks:
      - wulusai
    depends_on:
      - peer0.org2.wulusai.net

#orderer
  orderer0.wulusai.net: #为了方便看 服务名跟域名相同
    extends: #继承
      file:   orderer0.yaml #继承的文件位置
      service: orderer0.wulusai.net #继承文件中的服务
    container_name: orderer0.wulusai.net #容器名字
    networks:
      - wulusai
    depends_on:
      - kafka1.wulusai.net
      - kafka2.wulusai.net
      - kafka3.wulusai.net
      - kafka4.wulusai.net

  orderer1.wulusai.net: #为了方便看 服务名跟域名相同
    extends: #继承
      file:   orderer1.yaml #继承的文件位置
      service: orderer1.wulusai.net #继承文件中的服务
    container_name: orderer1.wulusai.net #容器名字
    networks:
      - wulusai
    depends_on:
      - kafka1.wulusai.net
      - kafka2.wulusai.net
      - kafka3.wulusai.net
      - kafka4.wulusai.net

  orderer2.wulusai.net: #为了方便看 服务名跟域名相同
    extends: #继承
      file:   orderer2.yaml #继承的文件位置
      service: orderer2.wulusai.net #继承文件中的服务
    container_name: orderer2.wulusai.net #容器名字
    networks:
      - wulusai
    depends_on:
      - kafka1.wulusai.net
      - kafka2.wulusai.net
      - kafka3.wulusai.net
      - kafka4.wulusai.net

  orderer3.wulusai.net: #为了方便看 服务名跟域名相同
    extends: #继承
      file:   orderer3.yaml #继承的文件位置
      service: orderer3.wulusai.net #继承文件中的服务
    container_name: orderer3.wulusai.net #容器名字
    networks:
      - wulusai
    depends_on:
      - kafka1.wulusai.net
      - kafka2.wulusai.net
      - kafka3.wulusai.net
      - kafka4.wulusai.net

#zookeeper
  zookeeper1.wulusai.net: #为了方便看 服务名跟域名相同
    extends: #继承
      file:   zookeeper1.yaml #继承的文件位置
      service: zookeeper1.wulusai.net #继承文件中的服务
    container_name: zookeeper1.wulusai.net #容器名字
    networks:
      - wulusai

  zookeeper2.wulusai.net: #为了方便看 服务名跟域名相同
    extends: #继承
      file:   zookeeper2.yaml #继承的文件位置
      service: zookeeper2.wulusai.net #继承文件中的服务
    container_name: zookeeper2.wulusai.net #容器名字
    networks:
      - wulusai

  zookeeper3.wulusai.net: #为了方便看 服务名跟域名相同
    extends: #继承
      file:   zookeeper3.yaml #继承的文件位置
      service: zookeeper3.wulusai.net #继承文件中的服务
    container_name: zookeeper3.wulusai.net #容器名字
    networks:
      - wulusai

#kafka
  kafka1.wulusai.net: #为了方便看 服务名跟域名相同
    extends: #继承
      file:   kafka1.yaml #继承的文件位置
      service: kafka1.wulusai.net #继承文件中的服务
    container_name: kafka1.wulusai.net #容器名字
    networks:
      - wulusai
    depends_on:
      - zookeeper1.wulusai.net
      - zookeeper2.wulusai.net
      - zookeeper3.wulusai.net

  kafka2.wulusai.net: #为了方便看 服务名跟域名相同
    extends: #继承
      file:   kafka2.yaml #继承的文件位置
      service: kafka2.wulusai.net #继承文件中的服务
    container_name: kafka2.wulusai.net #容器名字
    networks:
      - wulusai
    depends_on:
      - zookeeper1.wulusai.net
      - zookeeper2.wulusai.net
      - zookeeper3.wulusai.net

  kafka3.wulusai.net: #为了方便看 服务名跟域名相同
    extends: #继承
      file:   kafka3.yaml #继承的文件位置
      service: kafka3.wulusai.net #继承文件中的服务
    container_name: kafka3.wulusai.net #容器名字
    networks:
      - wulusai
    depends_on:
      - zookeeper1.wulusai.net
      - zookeeper2.wulusai.net
      - zookeeper3.wulusai.net

  kafka4.wulusai.net: #为了方便看 服务名跟域名相同
    extends: #继承
      file:   kafka4.yaml #继承的文件位置
      service: kafka4.wulusai.net #继承文件中的服务
    container_name: kafka4.wulusai.net #容器名字
    networks:
      - wulusai
    depends_on:
      - zookeeper1.wulusai.net
      - zookeeper2.wulusai.net
      - zookeeper3.wulusai.net

#peer
  peer0.org1.wulusai.net:
    container_name: peer0.org1.wulusai.net
    extends:
      file:  docker-compose-peer0org1.yaml
      service: peer0.org1.wulusai.net
    networks:
      - wulusai
    depends_on:
      - orderer1.wulusai.net
      - orderer2.wulusai.net
      - orderer3.wulusai.net
      - orderer0.wulusai.net

#  peer1.org1.wulusai.net:
#    container_name: peer1.org1.wulusai.net
#    extends:
#      file:  base/docker-compose-base.yaml
#      service: peer1.org1.wulusai.net
#    networks:
#      - wulusai

  peer0.org2.wulusai.net:
    container_name: peer0.org2.wulusai.net
    extends:
      file:  docker-compose-peer0org2.yaml
      service: peer0.org2.wulusai.net
    networks:
      - wulusai
    depends_on:
      - orderer1.wulusai.net
      - orderer2.wulusai.net
      - orderer3.wulusai.net
      - orderer0.wulusai.net

#  peer1.org2.wulusai.net:
#    container_name: peer1.org2.wulusai.net
#    extends:
#      file:  base/docker-compose-base.yaml
#      service: peer1.org2.wulusai.net
#    networks:
#      - wulusai

  p0o1cli:
    container_name: p0o1cli
    extends:
      file:  docker-compose-peer0org1.yaml
      service: p0o1cli
    networks:
      - wulusai
    depends_on:
      - orderer1.wulusai.net
      - orderer2.wulusai.net
      - orderer3.wulusai.net
      - orderer0.wulusai.net
      - peer0.org1.wulusai.net
      - ca0.wulusai.net


  p0o2cli:
    container_name: p0o2cli
    extends:
      file:  docker-compose-peer0org2.yaml
      service: p0o2cli
    networks:
      - wulusai
    depends_on:
     - orderer1.wulusai.net
     - orderer2.wulusai.net
     - orderer3.wulusai.net
     - orderer0.wulusai.net
     - peer0.org2.wulusai.net
     - ca1.wulusai.net



