version: '2'

services:

  orderer3.wulusai.net:
    container_name: orderer3.wulusai.net
    image: hyperledger/fabric-orderer:latest
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=wulusai_default
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      #- ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LISTENPORT=37050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]

      - ORDERER_KAFKA_RETRY_LONGINTERVAL=10s
      - ORDERER_KAFKA_RETRY_LONGTOTAL=100s
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
      #- ORDERER_KAFKA_BROKERS=[192.168.100.201:9092,192.168.100.202:9092,192.168.100.203:9092,192.168.100.204:9092]
      - ORDERER_KAFKA_BROKERS=[0.0.0.0:9092,0.0.0.0:10092,0.0.0.0:11092,0.0.0.0:12092]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/wulusai.net/orderers/orderer3.wulusai.net/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/wulusai.net/orderers/orderer3.wulusai.net/tls/:/var/hyperledger/orderer/tls
    networks:
      default:
        aliases:
          - wulusai
    ports:
#      - 7050:7050
      - 37050:37050
    extra_hosts:
      #      - kafka1:192.168.100.201
      #      - kafka2:192.168.100.202
      #      - kafka3:192.168.100.203
      #      - kafka4:192.168.100.204
      - kafka1.wulusai.net:0.0.0.0
      - kafka2.wulusai.net:0.0.0.0
      - kafka3.wulusai.net:0.0.0.0
      - kafka4.wulusai.net:0.0.0.0